Effects refactor, bump required SDK version
- Удалена устаревшая реализация эффектов инвертирования цветов и разрыва экрана (effects.rpy);
* Опциональный улучшайзер эффекта разрыва экрана стал обязательным и был немного переписан (effects_tear.rpy);
(i) Обе вышеупомянутые правки устраняют ошибку `AttributeError: 'NoneType' object has no attribute 'width'` во время исполнения `screenshot_srf()` на 8.3.x
* Повышены требования к версии движка (lockdown_check.rpy).